# formulate environment
FROM python:latest
# Copy the current directory (.) to the ./app folder in the docker image
COPY . /app
# Make the working path of the docker image
WORKDIR /app
# install dependencies
RUN pip install numpy
RUN pip install matplotlib
RUN pip install pandas

CMD ["python", "plot.py"]

#commands to run

# docker build ./ -t plot
# docker images
# docker run plot
# This command can generate a container (virtual machine)

# docker ps -a
# docker cp <container id from ps -a>:/app/plot.png ./
