# 制定环境
FROM python:latest
# 把当前目录（.） 复制到docker image中./app文件夹
COPY . /app
# 制定docker image的工作路径
WORKDIR /app
# install dependencies
RUN pip install numpy
RUN pip install matplotlib
RUN pip install pandas

CMD ["python", "plot.py"]

#commands to run

# docker build ./ -t plot
# docker images
# docker run plot
# 这个命令就可以生成container（虚拟机）

# docker ps -a
# docker cp <container id from ps -a>:/app/plot.png ./